using System.ComponentModel.DataAnnotations;

namespace NotesAndDutiesAPI.Models
{
    //Class that represents a user
    public class UserModel
    {
        [Key]
        public int UserId { get; set; }

        public string Username { get; set; }

        public string Password { get; set; }

        public string EmailAddress { get; set; }

        public string Role { get; set; }
    }

    // UserModel DTO that has no Id since its meant to be autogenerated
    public class UserModelDto
    {
        public string Username { get; set; }

        public string Password { get; set; }

        public string EmailAddress { get; set; }

        public string Role { get; set; }
    }

    // DTO containing only the data required for authentication
    public class UserLogin
    {
        public string Username { get; set; }

        public string Password { get; set; }
    }
}